GET http://localhost:8081/hello

###

#使用访问令牌访问
GET http://localhost:8081/hello
Authorization: Bearer eyJraWQiOiJlZjI3MTg0NS03MWIwLTQzYmQtYmEyZi1mZjVjMzdmMDU2MGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ5eWl0amF2YTEiLCJhdWQiOiJ5eWl0amF2YTEiLCJuYmYiOjE2NTA5NDA1NjUsInNjb3BlIjpbImFjY2Vzcy1oZWxsbyJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY1MDk0MjM2NSwiaWF0IjoxNjUwOTQwNTY1fQ.HilWHCYCEBS4bbijdS8ckhzKGxed7gbh5tEDH0h2OA2Ii3CUT5acUOvh9UoNOnLg49vHp7LIUVa-Q6qNAmjw5t2PcD1daisQ5KQolHz0da1IevKHHBXNTLQglQj9midhzsNjOLw11Kwk4t9A5RLaGwuUmLQqf44V-1-6FEP-_dN1BTlswMFkDETGvMeQe2QqO9y_Z6HnjArk7SrIH45wzqn1x4Ois3tUmvO1mGirrDUonpHAuVif6W1gpcOhNPcYv-2NMqkBi4Laf0F2I-LcT1rt53iAWCz5GnOMkxim0uVVS_5vEAF8-iYY-bd1SBC7azcZWA2LsvJeCyX-WKwp8A

###